version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_server
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  server:
    build: ./
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${APP_MONGO_DB}?authSource=admin
      - APP_SECRET=${APP_SECRET}
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - /data/db:/data/db
      - ./scripts/:/docker-entrypoint-initdb.d/
